name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: docker://sandrokeil/typescript:latest
    - name: Run a multi-line script
      run: |
        echo Ahoy!
        echo "Here's the current version of typescript: "
        tsc -v
