name: CI/CD

on:
  release:
    types:
      - published

env:
  ARTIFACT_NAME: ${{ 'minesweeper-compiled' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      ARTIFACT_PATH: artifact
      ASSET_NAME: minesweeper.zip
      ASSET_TYPE: application/zip
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Compile the source
        run: tsc --outDir "${ARTIFACT_PATH}/dist"

      - name: Prepare artifact
        run: mv index.html require.js main.js styles.css LICENSE assets ${ARTIFACT_PATH}

      - name: Prepare release asset
        run: zip -r ${ASSET_NAME} ${ARTIFACT_PATH}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: "./${ARTIFACT_PATH}"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${ASSET_NAME}"
          asset_name: ${ASSET_NAME}
          asset_content_type: ${ASSET_TYPE}

  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-20.04
  #   env:
  #     AWS_S3_BUCKET: rdlf0-minesweeper
  #     AWS_DEFAULT_REGION: us-east-2
  #   environment:
  #     name: production
  #     url: "http://${{ env.AWS_S3_BUCKET }}.s3-website.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com"
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: ${{ env.ARTIFACT_NAME }}

  #     - name: Upload to S3
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         aws s3 sync \
  #             '${{ env.ARTIFACT_NAME }}' s3://$AWS_S3_BUCKET \
  #             --no-progress \
  #             --acl public-read
