name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        
      - name: Pull a typescript-ready docker container
        uses: docker://sandrokeil/typescript:latest
      
      - name: Compile the source
        run: |
          tsc
          ls -l
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: minesweeper-compiled
          path: dist
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: minesweeper-compiled
      
      - name: Test - list contents
        run: ls -l
