name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        
      - name: Pull a typescript-ready docker container
        uses: docker://sandrokeil/typescript:latest
      
      - name: Compile the source
        run: tsc --sourceMap false --outDir artifact/dist
        
      - name: Prepare artifact
        run: mv index.html require.js styles.css artifact
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: minesweeper-compiled
          path: artifact
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: minesweeper-compiled
          
      - name: Upload to S3
        run: aws s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET \
                --no-progress \
	              --acl public-read
        env:
          SOURCE_DIR: './minesweeper-compiled'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
