name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: docker://sandrokeil/typescript:latest
      - name: Run a multi-line script
        run: |
          echo Ahoy!
          echo "Here's the current version of typescript: "
          tsc -v
          pwd
          ls -l
