name: CI/CD

on:
  release:
    types:
      - published

env:
  ARTIFACT_NAME: ${{ 'minesweeper-compiled' }}
  ARTIFACT_PATH: ${{ 'artifact' }}
  ASSET_NAME: ${{ 'minesweeper.zip' }}
  ASSET_TYPE: ${{ 'application/zip' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Compile the source
        run: tsc --outDir ${{ env.ARTIFACT_PATH }}/dist

      - name: Prepare artifact
        run: mv index.html require.js main.js styles.css LICENSE assets ${{ env.ARTIFACT_PATH }}

      - name: Prepare release asset
        run: zip -r ${{ env.ASSET_NAME }} ${{ env.ARTIFACT_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.ARTIFACT_PATH }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: ${{ env.ASSET_TYPE }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://rdlf0-minesweeper.s3-website.us-east-2.amazonaws.com/
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Upload to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 sync \
              '${{ env.ARTIFACT_NAME }}' s3://$AWS_S3_BUCKET \
              --no-progress \
              --acl public-read
