# name: Comment released PRs

# on:
#   release:
#     types:
#       - published

# jobs:
#   comment:
#     name: Comment released PRs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Comment released PRs
#         uses: rdlf0/comment-released-prs-action@v2
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
