name: Comment Released PRs

on:
  release:
    types:
      - published

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: rdlf0/comment-released-prs-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
