name: Comment released PRs

on:
  release:
    types:
      - published

jobs:
  comment:
    name: Comment released PRs
    runs-on: ubuntu-24.04
    permissions:
      contents: read           # read the release and its commits
      pull-requests: write     # comment on and label the released PRs
    steps:
      - name: Comment released PRs
        uses: rdlf0/comment-released-prs-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add-label: true
