name: Comment Released PRs

on:
  release:
    types:
      - published

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: rdlf0/comment-released-prs-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
