name: Compilability check

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Compile
      run: tsc --noEmit
