name: Release

on:
  release:
    types:
      - published

env:
  ARTIFACT_NAME: minesweeper-compiled

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_PATH: artifact
      ASSET_NAME: minesweeper.zip
      ASSET_TYPE: application/zip
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Compile the source
        run: tsc --outDir "${ARTIFACT_PATH}/dist"

      - name: Prepare artifact
        run: mv index.html require.js main.js styles.css favicon.svg robots.txt sitemap.xml manifest.webmanifet sw.js LICENSE assets $ARTIFACT_PATH

      - name: Prepare release asset
        run: zip -r $ASSET_NAME $ARTIFACT_PATH

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.ARTIFACT_PATH }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: ${{ env.ASSET_TYPE }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    env:
      AWS_S3_BUCKET: theminesweeper.com
      AWS_REGION: us-east-2
      AWS_ROLE: arn:aws:iam::067429979131:role/github_actions_minesweeper
    environment:
      name: production
      url: "https://${{ env.AWS_S3_BUCKET }}"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: .github/workflows/helpers/s3-sync.sh
