name: Release

on:
  release:
    types:
      - published

env:
  ARTIFACT_NAME: minesweeper-compiled

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_PATH: artifact
      ASSET_NAME: minesweeper.zip
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Compile the source
        run: tsc --outDir "${ARTIFACT_PATH}/dist"

      - name: Prepare artifact
        run: mv index.html require.js main.js styles.css favicon.svg robots.txt sitemap.xml manifest.webmanifest sw.js LICENSE assets $ARTIFACT_PATH

      - name: Prepare release asset
        run: zip -r $ASSET_NAME $ARTIFACT_PATH

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.ARTIFACT_PATH }}

      - name: Upload release asset
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "./${{ env.ASSET_NAME }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    env:
      AWS_S3_BUCKET: theminesweeper.com
      AWS_REGION: us-east-2
      AWS_ROLE: arn:aws:iam::067429979131:role/github_actions_minesweeper
    environment:
      name: production
      url: "https://${{ env.AWS_S3_BUCKET }}"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          declare -a files=(
          [0]="index.html"
          [1]="*.js"
          [2]="*.css"
          [3]="*.svg"
          [4]="*.png"
          [5]="*.webmanifest"
          [6]="*.txt"
          [7]="*.xml"
          [8]="LICENSE"
          )

          declare -a caches=(
          [0]="no-caches"
          [1]="max-age=31536000 immutable"
          [2]="max-age=31536000 immutable"
          [3]="max-age=31536000 immutable"
          [4]="max-age=31536000 immutable"
          [5]="max-age=31536000 immutable"
          [6]="max-age=31536000 immutable"
          [7]="max-age=31536000 immutable"
          [8]=""
          )

          declare -a contentTypes=(
          [0]="text/html; charset=utf-8"
          [1]="application/javascript; charset=utf-8"
          [2]="text/css; charset=utf-8"
          [3]="image/svg+xml; charset=utf-8"
          [4]="image/png; charset=utf-8"
          [5]="application/manifest+json; charset=utf-8"
          [6]="text/plain; charset=utf-8"
          [7]="application/xml; charset=utf-8"
          [8]=""
          )

          for i in "${!files[@]}"
          do
              echo "Uploading ${files[$i]}"

              aws s3 sync $ARTIFACT_NAME s3://$AWS_S3_BUCKET \
                    --delete \
                    --acl public-read \
                    --exclude "*" \
                    --include "${files[$i]}" \
                    --cache-control "${caches[$i]}" \
                    --content-type "${contentTypes[$i]}"
          done
